import type { Metadata } from "next";
import { Inter, Merienda } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./GlobalRedux/reduxProvider";

const Merienda_init = Merienda({
    subsets: ["latin"],
    weight: ["500", "600", "700", "800"],
    variable: "--font-merienda",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${inter.className} ${Merienda_init.variable}`}>
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    );
}
